# fly.toml app configuration file generated for btc-watchdog on 2025-07-22T14:29:47-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'btc-watchdog'
primary_region = 'lax'

[build]

[env]
  COINBASE_WS_URL = 'wss://ws-feed.exchange.coinbase.com'
  DB_PATH = '/data/btc_price_history.db'
  HEARTBEAT_PATH = '/data/btc_logger_heartbeat.txt'
  LOG_PATH = '/data/btc_price_log.txt'
  TIMEZONE = 'America/New_York'

[[mounts]]
  source = 'btc_data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
