#!/bin/bash

# BTC Price Watchdog - Complete Sharing Package
# This is the ONE way to share the service - both live API and source code

echo "🚀 BTC Price Watchdog - Complete Service Package"
echo "================================================"
echo ""
echo "✅ LIVE SERVICE (Ready to use now):"
echo "🌐 https://btc-watchdog.fly.dev"
echo ""
echo "📊 API Endpoints:"
echo "   • Health: https://btc-watchdog.fly.dev/health"
echo "   • Latest Price: https://btc-watchdog.fly.dev/latest"
echo "   • Historical Data: https://btc-watchdog.fly.dev/prices"
echo "   • Statistics: https://btc-watchdog.fly.dev/stats"
echo "   • Dashboard: https://btc-watchdog.fly.dev/dashboard.html"
echo ""
echo "🔧 Quick Test:"
echo "   curl https://btc-watchdog.fly.dev/latest"
echo ""
echo "📦 SOURCE CODE & DEPLOYMENT:"
echo "🔗 GitHub Repository: https://github.com/micpistol/btc-price-watch.git"
echo ""
echo "📖 Documentation:"
echo "   • Quick Start: https://github.com/micpistol/btc-price-watch/blob/main/QUICK_START.md"
echo "   • Setup Guide: https://github.com/micpistol/btc-price-watch/blob/main/SETUP.md"
echo "   • API Docs: https://github.com/micpistol/btc-price-watch/blob/main/API.md"
echo ""
echo "🎯 What You Get:"
echo "   ✅ Live API service (use immediately)"
echo "   ✅ Complete source code (deploy your own)"
echo "   ✅ Step-by-step setup guide"
echo "   ✅ API documentation with examples"
echo "   ✅ Test scripts and templates"
echo "   ✅ Mobile-responsive dashboard"
echo ""
echo "🛠️ Two Ways to Use:"
echo "   1. 🚀 Use the live service (immediate access)"
echo "   2. 🏗️  Deploy your own instance (full control)"
echo ""
echo "💡 Getting Started:"
echo "   1. Test the live service with the URLs above"
echo "   2. Clone the repo if you want your own instance"
echo "   3. Follow the setup guide for deployment"
echo ""
echo "🎉 Copy and paste this entire message to share!" 